### ISSUE TITLE
preset issue with windows

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#81] opened 2020-11-19 19:22 UTC
shift + click on any preset slot only load it but cannot save the slot (tested in ui.preset-help)
Sending "store" message works.

**Comment by 60-hz** [comment] 2020-11-20 18:06
Transfering all pd files in a folder without space return same problem. When "write" command is sent: same error message from pd and a blank preset file is created.

**Comment by uliss** [comment] 2020-11-22 14:56
Is it only windows issue?

Can't reproduce on mac, my steps are:

1. change some ui values
2. shift+click on preset button to store preset in memory
3. click on other preset button to select other preset
4. click on previous preset button to select first preset (all values are changed back)

**Comment by 60-hz** [comment] 2020-11-22 16:19
Yes, with OSX it works, only windows have this issue.  It looks like the shift key is not registered under windows.

**Comment by uliss** [comment] 2020-12-12 00:45
should be fixed in upcoming release

**Closed** 2020-12-20 08:51 UTC
