### ISSUE TITLE
Crash when using tilde symbol

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#116] opened 2021-03-12 17:04 UTC
Everytime I make the key combination (Alt + N) for Tilde, in Pd-ceammc_2021.03, pd crash. Works ok with Pd-0.51-4 vanilla version.

"[tcl:8.6.6 git:v2021.03-5-g4dde7d146] a quitté de manière imprévue."

Terminal  output:

2021-03-12 18:00:25.118 Wish[14217:1020379] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[__NSCFConstantString characterAtIndex:]: Range or index out of bounds'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff304c08d7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff69106a9e objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff3056f806 _CFThrowFormattedException + 194
	3   CoreFoundation                      0x00007fff3056f831 -[__NSCFString getCharacters:range:].cold.1 + 0
	4   CoreFoundation                      0x00007fff304202bc -[__NSCFString characterAtIndex:] + 95
	5   Tk                                  0x00007fff3dfcef11 TkpInitKeymapInfo + 720
	6   Tk                                  0x00007fff3dfd4b52 Tk_MacOSXSetupTkNotifier + 839
	7   Tcl                                 0x00007fff3decf27e Tcl_DoOneEvent + 305
	8   Tk                                  0x00007fff3df34f48 Tk_MainLoop + 45
	9   Tk                                  0x00007fff3df40502 Tk_MainEx + 1549
	10  Wish                                0x0000000109d1b523 Wish + 9507
	11  libdyld.dylib                       0x00007fff6a2a5cc9 start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
gui socket 6 - 
closing audio...
closing MIDI...
... done.

**Comment by njazz** [comment] 2021-03-12 17:22
confirmed on my 10.12.6, thanks

some notes:

- copy-pasting this symbol works ok
- this is "SMALL TILDE" unicode symbol, as in "ñ", not the 'real' ~ one, it doesn't work in object names anyway

**Comment by uliss** [comment] 2021-03-12 23:28
Seems to be fixed by using Tcl8.6.10
https://github.com/uliss/pure-data/releases/tag/v2021.03

**Comment by 60-hz** [comment] 2021-03-13 00:24
It is fixed!

**Closed as completed** 2021-03-13 09:49 UTC
Labels: bug
