### ISSUE TITLE
[ceammc] [dispatch] subscriber not found #5249597440

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#206] opened 2023-11-20 12:27 UTC
This message happen to console when closing help path of [snd.play~] while reading a file.

`[ceammc] [dispatch] subscriber not found #5249597440`

**Comment by uliss** [comment] 2023-11-20 21:32
Actually this is not a bug, but rather annoying message, when subscribed object destroyed, but worker thread is sending notification.

**Comment by uliss** [comment] 2024-05-04 01:14
this should be fixed in the upcoming release

**Closed as completed by uliss** 2024-05-04 01:14 UTC
Labels: enhancement
