### ISSUE TITLE
[string*] objets error in argument

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#139] opened 2021-10-29 14:30 UTC
[string*] objets refuse ":" character in arguments and returns:

[string] error while parsing ':': unmatched lexer input: ':'syntax error, unexpected LEXER_ERROR, expecting end of string
:
^

OSX 10.15.4 pd-0.51-4 and ceammc v0.9.3

**Comment by uliss** [comment] 2021-10-29 17:34
This is not a bug, but a consequence of support unified syntax for all ceammc objects.
The reason is additional ceammc argument expansion.

All Pd object supports expansion of dollar arguments: $0, $1 etc...

CEAMMC expands following expressions:

- pi() -> π number
- e() -> e number
- bs() -> patch blocksize
- sr() -> patch samplerate
- mtof() -> MIDI to freq conversion
- ftom() -> freq to MIDI conversion
- env(%VAR%) -> get environment variable
- db2amp() -> dbfs value to amp
- amp2db -> amp value to dbfs
- seq(FROM TO STEP) -> numeric sequence generators
- repeat(N ARGS..) -> repeat N times
- revert(ARGS) -> reverse args order
- rtree(ARGS) -> rtree syntax pattern
- euclid(K N) -> euclid pattern rhythm syntax
- expr("expression") -> calc math expression

![Снимок экрана 2021-10-29 в 20 16 34](https://user-images.githubusercontent.com/350661/139476337-dc635a23-5c23-4a66-b955-cbad117c84bf.png)

Also ceammc support different data types with their syntax:

- MList (multidimensional lists) -> (1 2 3 (3 4 5))
- Dict (dictionaries) -> [a: 1 b: 123]
- Set (sets) -> Set(1 2 3)

![Снимок экрана 2021-10-29 в 20 25 59](https://user-images.githubusercontent.com/350661/139477415-753d2758-6ed9-454b-bbcb-de1497268895.png)

So, some characters like ``:``, ``(``, ``)`` and others are treated as **special characters**. 
You can use them by enclosing into ``""``.  Also you can use spaces.


![Снимок экрана 2021-10-29 в 20 34 21](https://user-images.githubusercontent.com/350661/139478386-dfc79591-398f-4897-b83c-8323d156c018.png)

**Comment by uliss** [comment] 2021-10-29 17:36
@60-hz the shorter answer is: use double quotes

```
[string ":"]
```

**Comment by 60-hz** [comment] 2021-10-30 12:57
Great thanks, I understand better now. Being able to use expr in all objets is a very neat feature. Is it documented somewhere?

**Comment by uliss** [comment] 2021-11-01 14:35
Not fully documented yet.
Seems that there should be separate documentation files for such things, not only object documentation.

**Comment by uliss** [comment] 2021-11-05 18:58
Closing and add create separate issue for documentation #148

**Closed as completed by uliss** 2021-11-05 18:58 UTC
Labels: not a bug
