### ISSUE TITLE
midi.kbd issues

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#115] opened 2021-03-12 14:34 UTC
OS X 10.12.6, Pd-ceammc 2021.03, 32 bit float
object doesn't react on first key press. If you hold the key you get repetitive notes

**Comment by 60-hz** [comment] 2021-03-12 16:23
confirmed, OSX 10.15.4

**Comment by uliss** [comment] 2021-03-12 18:04
Ok, it seems to be Tcl/Tk issue

**Comment by uliss** [comment] 2021-03-12 23:27
Seems to be fixed by using Tcl8.6.10
https://github.com/uliss/pure-data/releases/tag/v2021.03

**Comment by 60-hz** [comment] 2021-03-13 00:23
Working nicely.

**Closed as completed** 2021-03-13 09:49 UTC
Labels: bug
