### ISSUE TITLE
ceammc lib crash with pd 0.52

### ISSUE THREAD

**Issue by 60-hz** [uliss/pure-data#140] opened 2021-10-29 14:35 UTC
Pd crash when loading ceammc library as soon as creating [declare -lib ceammc]
pd-0.52-0test1.macos and ceammc lib v0.9.3

**Comment by porres** [comment] 2021-11-23 09:58
not sure if anything in ceammc messes with audio setting, I had an external which did that crashed like that as it changed now.

**Comment by 60-hz** [comment] 2021-11-23 10:10
For more infos, here is the print log using -verbose -stderr with pd-0.52-test2 under OSX 10.15.4 and ceammc lib 0.9.4:

`Pd-0.52.0 ("test2") compiled 01:52:04 Nov 18 2021
float precision = 32 bits
verbose(4): input channels = 2, output channels = 2
port 49548
"/Users/username/Desktop/distrib/Pd-0.52-0test2.app/Contents/Resources/../MacOS/Pd" 49548
Waiting for connection request... 
... connected
verbose(4): tried /Users/username/Documents/Pd/ceammc.d_fat and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc.d_amd64 and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc.pd_darwin and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc.so and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc/ceammc.d_fat and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc/ceammc.d_amd64 and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc/ceammc.pd_darwin and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc/ceammc.so and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc.pd and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc.pat and failed
verbose(4): tried /Users/username/Documents/Pd/ceammc/ceammc.pd and failed
verbose(4): tried /Users/username/Documents/Pd/externals/ceammc.d_fat and failed
verbose(4): tried /Users/username/Documents/Pd/externals/ceammc.d_amd64 and failed
verbose(4): tried /Users/username/Documents/Pd/externals/ceammc.pd_darwin and failed
verbose(4): tried /Users/username/Documents/Pd/externals/ceammc.so and failed
verbose(4): tried /Users/username/Documents/Pd/externals/ceammc/ceammc.d_fat and failed
verbose(4): tried /Users/username/Documents/Pd/externals/ceammc/ceammc.d_amd64 and succeeded
verbose(4): [ceammc] new data type MList is registered with id: 257
verbose(4): [ceammc] new data type String is registered with id: 258
register loader: libsndfile
register loader: coreaudio
register loader: minimp3
verbose(4): [ceammc] new data type Set is registered with id: 259
verbose(4): [ceammc] new data type Env is registered with id: 260
verbose(4): [ceammc] new data type MidiStream is registered with id: 261
verbose(4): [ceammc] new data type MidiTrack is registered with id: 262

CEAMMC library
       Centre for Electroacoustic Music Moscow Conservatory, © 2016-2021
       authors: Serge Poltavsky and Alex Nadzharov
       arch: 64-bit
       precision: float
       path: /Users/username/Documents/Pd/externals/ceammc
       version: 0.9.4
       url: https://github.com/uliss/pure-data
        pd instance: false
       license: GPL-3
       build date: 'Nov 18 2021'

[ceammc] distribution: external deken
zsh: segmentation fault   -verbose -stderr`

**Comment by nburge** [comment] 2021-12-21 14:38
I installed the new PD vanilla 0.52-1 today and it crashed immediately when ceammc was in the startup preferences. I installed ceammc again from deken to be the latest version but it still crashes.

**Comment by sebshader** [comment] 2022-01-29 07:10
I got the same thing (which is a segfault). here are the relevant lines in the crash report:
```
Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libceammc_core.dylib          	0x000000010e105f33 ceammc::pd::currentListOfExternals() + 115
1   ???                           	0x00007ffd42837a18 0 + 140725719366168
```

**Comment by sebshader** [comment] 2022-01-29 07:38
perhaps the issue is that it just needs to be recompiled, some things were changed in m_imp.h. (though not in t_class itself, but the size of t_methodentry pointed to by a pointer in t_class.. dunno why that would change things though since pointers are all the same size..)

**Comment by sebshader** [comment] 2022-01-29 07:46
I think it might have something to do with pd's m_imp.h having a different t_methodentry than ceammc's t_methodentry (me_arg was changed to unsigned int)
recompiling with an updated m_imp.h may fix it

**Comment by 60-hz** [comment] 2022-02-03 22:57
I tried to compile under OSX but I had many problems and I am not used to cmake.
But I would be very happy to be able to use pd-0.52 and new features and ceammc for my next workshop.

**Comment by wkc1986** [comment] 2022-02-09 17:38
> I got the same thing (which is a segfault). here are the relevant lines in the crash report:
> 
> ```
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libceammc_core.dylib          	0x000000010e105f33 ceammc::pd::currentListOfExternals() + 115
> 1   ???                           	0x00007ffd42837a18 0 + 140725719366168
> ```

Reproduced this error message,
macOS 12.1
M1 Pro
Pd-0.52-1-really

**Comment by uliss** [comment] 2022-11-20 00:11
Fixed in newest pre-release, although not uploaded in deken yet

![Снимок экрана 2022-11-20 в 03 08 56](https://user-images.githubusercontent.com/350661/202876532-bf2273d9-18b7-4cc9-a03a-a99123df2d18.png)

**Closed as completed by uliss** 2022-11-20 00:11 UTC
Labels: bug
