### ISSUE TITLE
hoa.2d.map with nsrc argument == 1 creates object with 3 inputs

### ISSUE THREAD

**Issue by njazz** [uliss/pure-data#98] opened 2021-01-02 07:53 UTC

**Comment by porres** [comment] 2021-01-02 15:56
saw the same and then it doesn't seem to work properly at all even if you're feeding a single input

**Comment by uliss** [comment] 2021-01-02 19:43
This is not a bug, but original behavoir object. Just not documented.
If nsec==1 first inlet is **input signal**, second inlet is **radius** and third is **angle**.

Thus object can be controlled at signal rate instead of control.

This case will be documented

**Comment by uliss** [comment] 2021-03-10 19:19
closing: documented and inlet tooltip added
<img width="384" alt="Снимок экрана 2021-03-10 в 22 18 08" src="https://user-images.githubusercontent.com/350661/110684767-9233cd00-81ee-11eb-97d4-abde4aba5f92.png">

**Closed as completed by uliss** 2021-03-10 19:19 UTC
Labels: question
