### ISSUE TITLE
ceammc 0.9: [hoa.2d.decoder~] crashes in binaural mode in OSX

### ISSUE THREAD

**Issue by DaviRaubach** [uliss/pure-data#80] opened 2020-11-05 18:01 UTC
I am in OSX 10.13.6 
[hoa.2d.decoder~] works fine in Pd vanilla, except in the binaural mode (I tried in different Pd versions, 0.50-1, for example).
When I try to create the object, Pd closes.

The same object works well in version 0.8 of ceammc, even with Pd 0.51-3test5.

**Comment by uliss** [comment] 2020-12-12 00:43
can't reproduce...

<img width="897" alt="Снимок экрана 2020-12-12 в 3 41 52" src="https://user-images.githubusercontent.com/350661/101967580-1d231c80-3c2c-11eb-8f65-fb5d26158161.png">

Could you check this version of external:
https://drive.google.com/file/d/1ibRlAk_5sSrX21Ed1Zz3542FTqWiyinY/view?usp=sharing

**Comment by DaviRaubach** [comment] 2021-01-02 18:45
Hi, sorry for this delay. 
Yes, it worked perfectly.
Thanks!

**Comment by uliss** [comment] 2021-01-13 05:01
closing

**Closed by uliss** 2021-01-13 05:01 UTC
Labels: bug
